### ISSUE TITLE
Доработки Front #2

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-web#120]
1. Поправить отображение (запрос) главных страниц типа `dev.creaty.club/desgin` 

2. Доработать шаблоны писем

3. Поправить Формы для зарегистрированных юзеров 
- В поле Name должно отображаться Только значение Name (сейчас и Name, и Last name приходит) 
- Поля Name и Email должны автозаполняться, однако должны оставаться доступными для редактирования юзеру 
(сейчас отображаются как disabled) 
![Image](https://user-images.githubusercontent.com/98054391/245616432-13f2f7ab-4261-4fd6-98a5-5f8fa8740861.png)

4. Ui дрочево предлагаю обсудить на встрече в Среду (до меня дошло, например, что у нас сайт пытается криво подстраиваться под Тёмные темы... и выглядит это не оч) 

5. Доработать flow при Регистрации ментора в системе (который уже есть у нас в базе) — это можем в Среду обсудить, как раз подготовлю более понятный flow. Изменения, которые будут нужны скорее всего 
— другой экран "успеха" при прохождении регистрации 
— добавление бейджа Ментора 
— по идее не нужно будет подтверждать email, соответственно будет другое письмо для отправки на почту ментора

Предварительно вот тут можно посмотреть слегка обновленный флоу —>>> [Figma](https://www.figma.com/file/SDax2M2ihMLduf6OtzqZF0/%F0%9F%9F%A3-Creaty-for-Dev-2.0?type=design&node-id=998-128548&t=qNUb8F5MsU2jzfOo-11)

**Comment by Creatyclub** [comment]
> 5. Доработать flow при Регистрации ментора в системе (который уже есть у нас в базе) — это можем в Среду обсудить, как раз подготовлю более понятный flow. Изменения, которые будут нужны скорее всего

Необходимо изменить API при авторизации менторов: 
— запрос по email  
— как-то нужно решить вопрос с обязательным полем Name для юзеров 
— придумать варианты + **обсудить это с Серегой**

**Comment by Creatyclub** [comment]
@lendmid  Дим, я же эту задачку могу уже закрывать?

**Comment by lendmid** [comment]
> @lendmid Дим, я же эту задачку могу уже закрывать?
пока нет, я перенесу в тест, когда все поправлю
