### ISSUE TITLE
React при билде убирает порт у базового URL

### ISSUE THREAD

**Issue by GentleEnvy** [Creaty-Co/creaty-web#13]
### Контекст

Базовый URL API указывается в переменной `REACT_APP_API_HOST` в корневом файле **.env**

### Проблема

Если в **.env** указать `REACT_APP_API_HOST="https://api.test.creaty.club:81"`, запросы всё равно будут идти на `https://api.test.creaty.club` (т.е. фактически на 443 порт, а не 81)

### Требуется

Не игнорировать порт

**Comment by mapcic** [comment]
Не понимаю, как это относится к клиентской стороне. Если при билде подменяется — то это проблема проблема на уровне сборки билда.

Алгорит поменять порт, после пересобрать:
![Screenshot from 2023-01-09 05-48-37](https://user-images.githubusercontent.com/7786821/211233958-5844d051-14c9-43fe-9da1-6b619fe81228.png)
![Screenshot from 2023-01-09 05-48-22](https://user-images.githubusercontent.com/7786821/211233960-4eab8f61-272a-466d-a96c-3b25fd8b71db.png)

Сборка на стороне клиента: `GENERATE_SOURCEMAP=false react-scripts build -- --profile`.
Более логики сборки нет.

**Comment by GentleEnvy** [comment]
Моя ошибка, надо обновлять образ перед деплоем
