### ISSUE TITLE
Ui баг в тексте в блоке Book sessions

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-web#200]
Не "тянется" **имя** ментора в блоке Book session для Mentoring session:

Как сейчас выглядит (то есть просто написано, что сессия "С", а с кем непонятно)
![Image](https://github.com/Creaty-Co/creaty-web/assets/98054391/1144545c-b617-4559-ad53-edf3e25b514e)

Как должно быть? Вместе с именем написано, то есть: Mentoring session with **Name**
![Image](https://github.com/Creaty-Co/creaty-web/assets/98054391/07bcf087-655c-4962-82f4-494c9ce79733)

**Comment by lendmid** [comment]
все та же проблема, что поломали json в админке. Поправил

**Comment by Creatyclub** [comment]
А мы знаем как это происходит у нас?😅 А то кажется не только формы от этого страдают 😬
