### ISSUE TITLE
Вернуть админку на клиенте с фокусом на функциональность i18N (редактора текстов на фронте)

### ISSUE THREAD

**Issue by Creatyclub** [Creaty-Co/creaty-web#92]

**Comment by Creatyclub** [comment]
- сделать рабочим только редактор i18n
- по is_staff я показываю навигацию для админки
- авторизация такая же, как и на сайте

**Comment by lendmid** [comment]
оценка 3 часа

**Comment by lendmid** [comment]
оценка не увеличилась, задеплоил админку на дев

![Image](https://github.com/Creaty-Co/creaty-web/assets/59531952/f8277fd9-1428-43d6-bc27-f76b367cdfba)
